import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Project Leaderboards</title>
        <meta
          name="keywords"
          content="leaderboards, games, projects, leaderboard, project leaderboards, project leaderboard"
        />
        <meta name="description" content="Play interconnected games." />
        <meta name="author" content="Areeb and The Areebers" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
